import { NextResponse } from "next/server";
import { loadTokens } from "@/lib/token-store";
import {
  ensureAutopilotState,
  generateTodayJobsIfNeeded,
  getNextRetryIso,
  saveAutopilotState,
  type ScheduledJob,
} from "@/lib/autopilot-store";
import { publishToChannels } from "@/lib/social-publisher";
import { validateContentGuardrails } from "@/lib/content-guardrails";
import { getLatestWinnerCaption } from "@/lib/experiment-store";
import { buildAutopilotCaptionFromContext } from "@/lib/autopilot-caption";
import { resolveAutopilotImageUrl } from "@/lib/autopilot-image";
import { listCompetitors } from "@/lib/competitor-store";
import { fetchResearchUsingWrapper } from "@/lib/research-wrapper";
import { getResearchSnapshot, replaceResearchSnapshot } from "@/lib/research-store";
import { listWeeklyTasks, upsertWeeklyTasks, type WeeklyContentTask } from "@/lib/task-folder-store";
import { getResearchPreferences } from "@/lib/research-preferences-store";
import { getUserIdFromRequest } from "@/lib/user-session";

const MAX_RETRIES = 3;
const HOURLY_REFRESH_MS = 60 * 60 * 1000;

function nextDateAtHour(offsetHours: number): string {
  const d = new Date();
  d.setHours(d.getHours() + offsetHours, 0, 0, 0);
  return d.toISOString();
}

function normalizeCaption(text: string): string {
  return text.replace(/\s+/g, " ").trim().toLowerCase();
}

export async function POST(request: Request) {
  const userId = getUserIdFromRequest(request);
  const tokens = await loadTokens(userId);
  if (!tokens) {
    return NextResponse.json(
      { error: "No connected account found. Connect account before processing queue." },
      { status: 401 }
    );
  }

  let state = await ensureAutopilotState(undefined, userId);
  if (!state.selectedPageId) {
    return NextResponse.json({ error: "Autopilot page is not selected in settings." }, { status: 400 });
  }

  state = generateTodayJobsIfNeeded(state);

  let researchRefreshed = false;
  let autoGenerated = 0;

  const lastRefreshTime = state.lastResearchRefreshAt ? new Date(state.lastResearchRefreshAt).getTime() : 0;
  const shouldRefreshResearch = Date.now() - lastRefreshTime >= HOURLY_REFRESH_MS;

  if (shouldRefreshResearch) {
    const competitors = await listCompetitors(userId);
    const userCompetitors = competitors.filter((item) => !item.isSeed);
    const preferences = await getResearchPreferences(userId);

    if (userCompetitors.length > 0) {
      const fetched = await fetchResearchUsingWrapper({
        competitors: userCompetitors.map((item) => ({ handle: item.handle, channel: item.channel })),
        platforms: preferences.platforms,
        categories: preferences.categories,
        categoryWeights: preferences.categoryWeights,
        customHashtags: preferences.customHashtags,
      });

      if (fetched.items.length > 0) {
        await replaceResearchSnapshot({
          items: fetched.items,
          trendingHashtags: fetched.trendingHashtags,
        }, userId);
        researchRefreshed = true;
        state.lastResearchRefreshAt = new Date().toISOString();

        const enabledChannels = state.rules
          .filter((rule) => rule.enabled && (rule.channel === "instagram" || rule.channel === "facebook"))
          .map((rule) => rule.channel as "instagram" | "facebook");

        const selectedPage = tokens.pages.find((item) => item.id === state.selectedPageId);
        const snapshot = await getResearchSnapshot(userId);
        const queue = await listWeeklyTasks(userId);
        const activeQueueCount = queue.filter((task) => task.status === "review" || task.status === "upcoming").length;

        if (selectedPage && enabledChannels.length > 0 && snapshot.items.length > 0 && activeQueueCount < 7) {
          const toCreate = 7 - activeQueueCount;
          const used = new Set(queue.map((task) => normalizeCaption(task.caption)));
          const nowIso = new Date().toISOString();

          const tasks: WeeklyContentTask[] = [];
          for (let index = 0; index < toCreate; index += 1) {
            const source = snapshot.items[index % snapshot.items.length];
            const channel = enabledChannels[index % enabledChannels.length];
            const trend = snapshot.trendingHashtags[index % Math.max(snapshot.trendingHashtags.length, 1)];
            const trendTag = trend?.tag ?? "#socialmedia";
            const preferred = preferences.customHashtags.slice(0, 6);
            const weightedCategories = Object.entries(preferences.categoryWeights)
              .sort((a, b) => b[1] - a[1])
              .slice(0, 2)
              .map(([category]) => `#${category.replace(/\s+/g, "")}`);

            let caption = `${source.title}\n\n${source.snippet.slice(0, 180)}\n\nSource insight from ${source.competitorHandle}. Use this angle with a clear CTA.\n\n${[...new Set([...(source.hashtags ?? []), trendTag, ...preferred, ...weightedCategories])].slice(0, 10).join(" ")}`;

            const base = normalizeCaption(caption);
            if (used.has(base)) {
              caption = `${caption}\n\nFresh angle ${index + 1}: focus on ${trendTag.replace("#", "")}.`;
            }
            used.add(normalizeCaption(caption));

            tasks.push({
              id: `auto-hourly-${Date.now()}-${index}`,
              channel,
              pageId: selectedPage.id,
              pageName: selectedPage.name,
              accountHandle: `@${selectedPage.name.toLowerCase().replace(/[^a-z0-9]+/g, "").slice(0, 18) || "account"}`,
              competitorHandle: source.competitorHandle,
              caption,
              research: {
                title: source.title,
                summary: source.snippet,
                sourceUrl: source.sourceUrl,
                inferredTopic: state.campaignTopic,
                basedOn: ["hourly_wrapper_research", "competitor_content", "trending_hashtags"],
              },
              imageUrl: resolveAutopilotImageUrl({
                preferredUrl: state.imageUrl,
                topic: `${state.campaignTopic ?? "social growth"} ${source.title}`,
                competitorHint: source.competitorHandle,
                caption,
                channel,
                seed: `${source.id}-${index}`,
              }),
              scheduledAt: nextDateAtHour(index + 1),
              status: "review",
              createdAt: nowIso,
            });
          }

          if (tasks.length > 0) {
            await upsertWeeklyTasks(tasks, userId);
            autoGenerated = tasks.length;
            state.lastAutoGenerateAt = new Date().toISOString();
          }
        }
      }
    }
  }

  const now = new Date();
  const dueJobs = state.jobs.filter((job) => {
    if (job.status !== "pending") return false;
    if (new Date(job.runAtIso) > now) return false;
    if (job.nextAttemptAtIso && new Date(job.nextAttemptAtIso) > now) return false;
    return true;
  });

  const updates = new Map<string, ScheduledJob>();
  let winnerCaptionUsed = 0;

  for (const job of dueJobs) {
    const rule = state.rules.find((item) => item.id === job.ruleId);
    const contextualCaption = await buildAutopilotCaptionFromContext({
      channel: job.channel,
      tone: rule?.tone,
      campaignTopic: state.campaignTopic,
      competitorHint: rule?.competitorId,
    });

    const winnerCaption = await getLatestWinnerCaption({
      channel: job.channel,
      pageId: job.pageId,
    }, userId);

    const preferContextual = Boolean(state.campaignTopic?.trim());
    const caption = preferContextual ? contextualCaption : winnerCaption ?? contextualCaption;

    if (winnerCaption && !preferContextual) {
      winnerCaptionUsed += 1;
    }

    const resolvedImageUrl = resolveAutopilotImageUrl({
      preferredUrl: state.imageUrl,
      topic: state.campaignTopic,
      competitorHint: rule?.competitorId,
      caption,
      channel: job.channel,
      seed: job.id,
    });

    const guardrails = validateContentGuardrails({
      caption,
      imageUrl: resolvedImageUrl,
      channel: job.channel,
    });

    if (!guardrails.ok) {
      updates.set(job.id, {
        ...job,
        status: "failed",
        attempts: (job.attempts ?? 0) + 1,
        lastAttemptAtIso: now.toISOString(),
        error: `Guardrail blocked content: ${guardrails.errors.join(" ")}`,
      });
      continue;
    }

    const result = await publishToChannels({
      tokens,
      pageId: job.pageId,
      channels: [job.channel],
      caption: guardrails.normalizedCaption,
      imageUrl: resolvedImageUrl,
    });

    const channelResult = result[job.channel];
    if (channelResult?.success) {
      updates.set(job.id, {
        ...job,
        status: "posted",
        attempts: (job.attempts ?? 0) + 1,
        nextAttemptAtIso: undefined,
        lastAttemptAtIso: now.toISOString(),
        resultId: channelResult.id,
        error: undefined,
      });
    } else {
      const attempts = (job.attempts ?? 0) + 1;
      const shouldRetry = attempts < MAX_RETRIES;
      updates.set(job.id, {
        ...job,
        status: shouldRetry ? "pending" : "failed",
        attempts,
        nextAttemptAtIso: shouldRetry ? getNextRetryIso(attempts, now) : undefined,
        lastAttemptAtIso: now.toISOString(),
        error: channelResult?.error ?? "Posting failed",
      });
    }
  }

  const nextJobs = state.jobs.map((job) => updates.get(job.id) ?? job);
  const nextState = {
    ...state,
    jobs: nextJobs,
  };
  await saveAutopilotState(nextState, userId);

  return NextResponse.json({
    processed: dueJobs.length,
    posted: Array.from(updates.values()).filter((item) => item.status === "posted").length,
    failed: Array.from(updates.values()).filter((item) => item.status === "failed").length,
    retried: Array.from(updates.values()).filter((item) => item.status === "pending" && item.error).length,
    winnerCaptionUsed,
    researchRefreshed,
    autoGenerated,
    queue: {
      total: nextJobs.length,
      pending: nextJobs.filter((item) => item.status === "pending").length,
      posted: nextJobs.filter((item) => item.status === "posted").length,
      failed: nextJobs.filter((item) => item.status === "failed").length,
    },
  });
}
